include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
  errors:
    invalid_assignment: error
    missing_return: error
    dead_code: warning
    unused_import: error

linter:
  rules:
    avoid_print: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    always_declare_return_types: true
